feat: upgrade module, add test instructions
Mint-System/Odoo-Apps-Partner-Contact pull request #3
Opened 2024-07-09 09:32 UTC by laszlokr

2024-07-09 15:26 UTC, janikvonrotz requested changes

2024-07-09 15:26 UTC, janikvonrotz commented on partner_ref_sequence/tests/test_partner_ref_sequence.py
Lets run the test.

2024-07-10 14:57 UTC, laszlokr commented on partner_ref_sequence/tests/test_partner_ref_sequence.py
![image](https://github.com/Mint-System/Odoo-Apps-Partner-Contact/assets/91263982/1ac185b1-4cea-42d1-92b6-44c6984606fb)

2024-07-11 06:44 UTC, janikvonrotz approved these changes

2024-07-11 09:28 UTC, merged